import 'package:flutter/cupertino.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

EdgeInsets padding16=EdgeInsets.all(16.sp);
EdgeInsets padding12=EdgeInsets.all(12.sp);
EdgeInsets padding8=EdgeInsets.all(8.sp);
EdgeInsets padding6=EdgeInsets.all(6.sp);
EdgeInsets padding2=EdgeInsets.all(2.sp);
EdgeInsets padding14=EdgeInsets.all(14.sp);
EdgeInsets padding16H=EdgeInsets.symmetric(horizontal:16.sp);
EdgeInsets padding12T=EdgeInsets.only(top:12.sp);
EdgeInsets padding6T=EdgeInsets.only(top:6.sp);
EdgeInsets padding16V=EdgeInsets.symmetric(vertical:16.sp);
EdgeInsets padding14H=EdgeInsets.symmetric(horizontal:14.sp);
EdgeInsets padding14V=EdgeInsets.symmetric(vertical:14.sp);
EdgeInsets padding12H=EdgeInsets.symmetric(horizontal:12.sp);
EdgeInsets padding12V=EdgeInsets.symmetric(vertical:12.sp);
EdgeInsets padding6H=EdgeInsets.symmetric(horizontal:6.sp);
EdgeInsets padding6V=EdgeInsets.symmetric(vertical:6.sp);
EdgeInsets padding16b24=EdgeInsets.all(16.sp).copyWith(bottom: 24.sp);
EdgeInsets paddingH16V6=EdgeInsets.symmetric(horizontal:16.sp,vertical: 6.sp);
EdgeInsets paddingH16V8=EdgeInsets.symmetric(horizontal:16.sp,vertical: 8.sp);